## 결측치 처리 (Missing Value Handling)

#### 결측치란 데이터 수집·저장 과정에서 값이 비어 있거나 누락된 데이터를 의미한다.

- 대부분의 ML 알고리즘은 결측치를 직접 처리할 수 없으므로, 모델 학습 전에 적절한 방법으로 처리해야 한다.
- 처리 방식에 따라 데이터의 분포와 모델 성능이 크게 달라질 수 있어, 데이터 특성과 결측 패턴에 맞는 전략을 선택하는 것이 중요하다.

#### 왜 결측치 처리가 필요한가?
- **모델 학습 불가**: 대부분의 알고리즘이 NaN 입력을 허용하지 않아 에러가 발생한다.
- **통계량 왜곡**: 결측치를 무시하면 평균·분산 등 통계량이 왜곡되어 분석 결과의 신뢰도가 떨어진다.
- **정보 손실 방지**: 결측치가 포함된 행을 무조건 삭제하면 유의미한 데이터까지 함께 소실될 수 있다.

#### 주요 결측치 처리 방법
| 방법 | 설명 | 적합 상황 |
|---|---|---|
| **상수 대체** | 특정 값(0, -1 등)으로 일괄 대체 | 결측 자체에 의미가 있거나, 단순 처리가 필요할 때 |
| **평균 대체** | 해당 컬럼의 평균값으로 대체 | 정규분포에 가까운 연속형 데이터 |
| **중앙값 대체** | 해당 컬럼의 중앙값으로 대체 | 이상치가 있거나 비대칭 분포인 데이터 |
| **최댓값/최솟값 대체** | 최대 또는 최소값으로 대체 | 최악/최선 시나리오를 가정할 때 |
| **최빈값 대체** | 가장 빈번한 값으로 대체 | 범주형(명목형·순서형) 데이터 |
| **선행값 대체 (ffill)** | 바로 이전 값으로 대체 | 시계열 데이터에서 이전 상태가 유지될 때 |
| **후행값 대체 (bfill)** | 바로 이후 값으로 대체 | 시계열 데이터에서 이후 값이 더 신뢰할 만할 때 |

### 1. 상수 대체
**사용 예:**
- 데이터 분석 초기에 간단한 대체가 필요한 경우
- 특정 값(예: 0 또는 -1)이 의미 있는 경우
- 데이터의 null 값이 특별한 의미가 없고, 단순히 빈 값으로 처리할 수 있을 때

**예시:**
- 제품의 재고 수량에서 결측값을 0으로 대체하여, 결측값이 있는 경우 해당 제품의 재고가 없음을 의미하도록 할 때

In [6]:
import pandas as pd

df = pd.read_csv("./dataset/null.csv")

In [7]:
df.head()

     A      B      C
0  5.0    0.0  376.0
1  3.0    0.0   94.0
2  3.0   91.0  141.0
3  NaN   78.0    NaN
4  2.0  104.0  376.0

In [8]:
## 상수 대체
df_cons = df.fillna(0)

df_cons.head()

     A      B      C
0  5.0    0.0  376.0
1  3.0    0.0   94.0
2  3.0   91.0  141.0
3  0.0   78.0    0.0
4  2.0  104.0  376.0

### 2. 평균 대체
**사용 예:**
- 연속형 데이터의 결측값을 처리할 때
- 데이터 분포가 정규분포에 가깝고, 평균값이 대표 값을 잘 나타낼 때
- 결측값이 많지 않고, 평균으로 대체해도 큰 왜곡이 없을 때

In [10]:
# 평균으로 결측값 대체
df_mean = df.fillna(df.mean())
print(df_mean)

      A           B           C
0   5.0    0.000000  376.000000
1   3.0    0.000000   94.000000
2   3.0   91.000000  141.000000
3   3.4   78.000000  228.869565
4   2.0  104.000000  376.000000
5   3.0    0.000000  329.000000
6   5.0   13.000000  376.000000
7   5.0   42.840909  235.000000
8   8.0   91.000000  141.000000
9   2.0   52.000000  235.000000
10  3.0   13.000000  282.000000
11  0.0   52.000000  376.000000
12  3.0   42.840909  329.000000
13  0.0  104.000000  329.000000
14  3.0   42.840909  376.000000
15  9.0   78.000000  188.000000
16  3.0   91.000000  376.000000
17  3.0   13.000000  188.000000
18  3.4  104.000000  141.000000
19  3.0    0.000000  228.869565
20  3.0   13.000000  329.000000
21  3.4   91.000000  228.869565
22  9.0   26.000000  141.000000
23  5.0    0.000000   94.000000
24  1.0  117.000000  376.000000
25  5.0   13.000000  141.000000
26  3.0  104.000000  188.000000
27  0.0    0.000000  329.000000
28  3.0    0.000000    0.000000
29  3.0   42.840909  329.000000
30  3.0   13.000000  141.000000
31  1.0   78.000000   94.000000
32  1.0   91.000000   94.000000
33  0.0    0.000000  329.000000
34  3.0   78.000000  329.000000
35  3.0    0.000000  141.000000
36  0.0    0.000000  282.000000
37  1.0   78.000000  228.869565
38  3.4   78.000000  188.000000
39  9.0   13.000000    0.000000
40  8.0   52.000000  188.000000
41  5.0    0.000000   94.000000
42  2.0    0.000000  329.000000
43  3.0   13.000000  329.000000
44  8.0   42.840909  376.000000
45  0.0   91.000000  376.000000
46  3.4   42.840909  141.000000
47  1.0   26.000000  141.000000
48  8.0   13.000000    0.000000
49  2.0   13.000000  141.000000

### 3. 중간값 대체
**사용 예:**
- 데이터에 극단값(outliers)이 존재하여 평균이 대표 값을 잘 나타내지 못할 때
- 데이터가 비대칭적으로 분포되어 있을 때
- 연속형 데이터에서 중앙값이 더 적합한 대표 값일 때

In [11]:
## 중간값 대체
df_median = df.fillna(df.median())
print(df_median)

      A      B      C
0   5.0    0.0  376.0
1   3.0    0.0   94.0
2   3.0   91.0  141.0
3   3.0   78.0  211.5
4   2.0  104.0  376.0
5   3.0    0.0  329.0
6   5.0   13.0  376.0
7   5.0   19.5  235.0
8   8.0   91.0  141.0
9   2.0   52.0  235.0
10  3.0   13.0  282.0
11  0.0   52.0  376.0
12  3.0   19.5  329.0
13  0.0  104.0  329.0
14  3.0   19.5  376.0
15  9.0   78.0  188.0
16  3.0   91.0  376.0
17  3.0   13.0  188.0
18  3.0  104.0  141.0
19  3.0    0.0  211.5
20  3.0   13.0  329.0
21  3.0   91.0  211.5
22  9.0   26.0  141.0
23  5.0    0.0   94.0
24  1.0  117.0  376.0
25  5.0   13.0  141.0
26  3.0  104.0  188.0
27  0.0    0.0  329.0
28  3.0    0.0    0.0
29  3.0   19.5  329.0
30  3.0   13.0  141.0
31  1.0   78.0   94.0
32  1.0   91.0   94.0
33  0.0    0.0  329.0
34  3.0   78.0  329.0
35  3.0    0.0  141.0
36  0.0    0.0  282.0
37  1.0   78.0  211.5
38  3.0   78.0  188.0
39  9.0   13.0    0.0
40  8.0   52.0  188.0
41  5.0    0.0   94.0
42  2.0    0.0  329.0
43  3.0   13.0  329.0
44  8.0   19.5  376.0
45  0.0   91.0  376.0
46  3.0   19.5  141.0
47  1.0   26.0  141.0
48  8.0   13.0    0.0
49  2.0   13.0  141.0

### 4. 최대값 대체
**사용 예:**
- 데이터의 특정 값이 매우 중요한 의미를 가질 때
- 결측값이 발생한 경우 최대값을 대체하는 것이 의미가 있을 때
- 데이터 분석 목적상 최고 값을 기준으로 결측값을 대체하는 것이 적절할 때

**예시:**
- 판매량 데이터에서 결측값을 최대 판매량으로 대체하여, 최악의 시나리오를 가정하고자 할 때
---
### 5. 최소값 대체
**사용 예:**
- 데이터의 특정 값이 매우 중요한 의미를 가질 때
- 결측값이 발생한 경우 최소값을 대체하는 것이 의미가 있을 때
- 데이터 분석 목적상 최저 값을 기준으로 결측값을 대체하는 것이 적절할 때

**예시:**
- 온도 데이터에서 결측값을 최소 온도로 대체하여, 최악의 시나리오를 가정하고자 할 때

In [12]:
## 최대/최소값 대체
df_max = df.fillna(df.max())
df_min = df.fillna(df.min())

### 6. 최빈값 대체
**사용 예:**
- 범주형 데이터의 결측값을 처리할 때
- 특정 범주의 빈도가 매우 높아 그 값으로 대체하는 것이 자연스러울 때
- 데이터가 명목형 또는 순서형일 때

In [13]:
## 최빈값 대체 -> dataframe의 최빈값을 구해주는 mode() 함수 사용
df_mode = df.fillna(df.mode().iloc[0])
print(df_mode)

      A      B      C
0   5.0    0.0  376.0
1   3.0    0.0   94.0
2   3.0   91.0  141.0
3   3.0   78.0  141.0
4   2.0  104.0  376.0
5   3.0    0.0  329.0
6   5.0   13.0  376.0
7   5.0    0.0  235.0
8   8.0   91.0  141.0
9   2.0   52.0  235.0
10  3.0   13.0  282.0
11  0.0   52.0  376.0
12  3.0    0.0  329.0
13  0.0  104.0  329.0
14  3.0    0.0  376.0
15  9.0   78.0  188.0
16  3.0   91.0  376.0
17  3.0   13.0  188.0
18  3.0  104.0  141.0
19  3.0    0.0  141.0
20  3.0   13.0  329.0
21  3.0   91.0  141.0
22  9.0   26.0  141.0
23  5.0    0.0   94.0
24  1.0  117.0  376.0
25  5.0   13.0  141.0
26  3.0  104.0  188.0
27  0.0    0.0  329.0
28  3.0    0.0    0.0
29  3.0    0.0  329.0
30  3.0   13.0  141.0
31  1.0   78.0   94.0
32  1.0   91.0   94.0
33  0.0    0.0  329.0
34  3.0   78.0  329.0
35  3.0    0.0  141.0
36  0.0    0.0  282.0
37  1.0   78.0  141.0
38  3.0   78.0  188.0
39  9.0   13.0    0.0
40  8.0   52.0  188.0
41  5.0    0.0   94.0
42  2.0    0.0  329.0
43  3.0   13.0  329.0
44  8.0    0.0  376.0
45  0.0   91.0  376.0
46  3.0    0.0  141.0
47  1.0   26.0  141.0
48  8.0   13.0    0.0
49  2.0   13.0  141.0

### 7. 선행값 대체
**사용 예:**
- 시계열 데이터의 결측값을 처리할 때
- 연속된 데이터에서 결측값이 이전 값과 동일할 가능성이 높을 때
- 결측값이 발생한 경우 이전 상태를 유지하는 것이 적절할 때

**예시:**
- 주식 가격 데이터에서 결측값을 이전 날의 가격으로 대체하여, 일시적인 데이터 손실을 보완할 때

In [14]:
## 최빈값 대체 -> dataframe의 최빈값을 구해주는 mode() 함수 사용
df_mode = df.fillna(df.mode().iloc[0])
print(df_mode)

      A      B      C
0   5.0    0.0  376.0
1   3.0    0.0   94.0
2   3.0   91.0  141.0
3   3.0   78.0  141.0
4   2.0  104.0  376.0
5   3.0    0.0  329.0
6   5.0   13.0  376.0
7   5.0    0.0  235.0
8   8.0   91.0  141.0
9   2.0   52.0  235.0
10  3.0   13.0  282.0
11  0.0   52.0  376.0
12  3.0    0.0  329.0
13  0.0  104.0  329.0
14  3.0    0.0  376.0
15  9.0   78.0  188.0
16  3.0   91.0  376.0
17  3.0   13.0  188.0
18  3.0  104.0  141.0
19  3.0    0.0  141.0
20  3.0   13.0  329.0
21  3.0   91.0  141.0
22  9.0   26.0  141.0
23  5.0    0.0   94.0
24  1.0  117.0  376.0
25  5.0   13.0  141.0
26  3.0  104.0  188.0
27  0.0    0.0  329.0
28  3.0    0.0    0.0
29  3.0    0.0  329.0
30  3.0   13.0  141.0
31  1.0   78.0   94.0
32  1.0   91.0   94.0
33  0.0    0.0  329.0
34  3.0   78.0  329.0
35  3.0    0.0  141.0
36  0.0    0.0  282.0
37  1.0   78.0  141.0
38  3.0   78.0  188.0
39  9.0   13.0    0.0
40  8.0   52.0  188.0
41  5.0    0.0   94.0
42  2.0    0.0  329.0
43  3.0   13.0  329.0
44  8.0    0.0  376.0
45  0.0   91.0  376.0
46  3.0    0.0  141.0
47  1.0   26.0  141.0
48  8.0   13.0    0.0
49  2.0   13.0  141.0

### 7. 선행값 대체
**사용 예:**
- 시계열 데이터의 결측값을 처리할 때
- 연속된 데이터에서 결측값이 이전 값과 동일할 가능성이 높을 때
- 결측값이 발생한 경우 이전 상태를 유지하는 것이 적절할 때

**예시:**
- 주식 가격 데이터에서 결측값을 이전 날의 가격으로 대체하여, 일시적인 데이터 손실을 보완할 때

In [17]:
## 선행값 대체

df_ffill = df.ffill()
print(df_ffill)

      A      B      C
0   5.0    0.0  376.0
1   3.0    0.0   94.0
2   3.0   91.0  141.0
3   3.0   78.0  141.0
4   2.0  104.0  376.0
5   3.0    0.0  329.0
6   5.0   13.0  376.0
7   5.0   13.0  235.0
8   8.0   91.0  141.0
9   2.0   52.0  235.0
10  3.0   13.0  282.0
11  0.0   52.0  376.0
12  3.0   52.0  329.0
13  0.0  104.0  329.0
14  3.0  104.0  376.0
15  9.0   78.0  188.0
16  3.0   91.0  376.0
17  3.0   13.0  188.0
18  3.0  104.0  141.0
19  3.0    0.0  141.0
20  3.0   13.0  329.0
21  3.0   91.0  329.0
22  9.0   26.0  141.0
23  5.0    0.0   94.0
24  1.0  117.0  376.0
25  5.0   13.0  141.0
26  3.0  104.0  188.0
27  0.0    0.0  329.0
28  3.0    0.0    0.0
29  3.0    0.0  329.0
30  3.0   13.0  141.0
31  1.0   78.0   94.0
32  1.0   91.0   94.0
33  0.0    0.0  329.0
34  3.0   78.0  329.0
35  3.0    0.0  141.0
36  0.0    0.0  282.0
37  1.0   78.0  282.0
38  1.0   78.0  188.0
39  9.0   13.0    0.0
40  8.0   52.0  188.0
41  5.0    0.0   94.0
42  2.0    0.0  329.0
43  3.0   13.0  329.0
44  8.0   13.0  376.0
45  0.0   91.0  376.0
46  0.0   91.0  141.0
47  1.0   26.0  141.0
48  8.0   13.0    0.0
49  2.0   13.0  141.0

### 8. 후행값 대체
**사용 예:**
- 시계열 데이터의 결측값을 처리할 때
- 연속된 데이터에서 결측값이 이후 값과 동일할 가능성이 높을 때
- 결측값이 발생한 경우 이후 상태를 유지하는 것이 적절할 때

**예시:**
- 센서 데이터에서 결측값을 이후의 값으로 대체하여, 센서가 정상 작동을 재개한 이후의 데이터를 신뢰할 때

In [18]:
df_bfill = df.bfill()
print(df_bfill)

      A      B      C
0   5.0    0.0  376.0
1   3.0    0.0   94.0
2   3.0   91.0  141.0
3   2.0   78.0  376.0
4   2.0  104.0  376.0
5   3.0    0.0  329.0
6   5.0   13.0  376.0
7   5.0   91.0  235.0
8   8.0   91.0  141.0
9   2.0   52.0  235.0
10  3.0   13.0  282.0
11  0.0   52.0  376.0
12  3.0  104.0  329.0
13  0.0  104.0  329.0
14  3.0   78.0  376.0
15  9.0   78.0  188.0
16  3.0   91.0  376.0
17  3.0   13.0  188.0
18  3.0  104.0  141.0
19  3.0    0.0  329.0
20  3.0   13.0  329.0
21  9.0   91.0  141.0
22  9.0   26.0  141.0
23  5.0    0.0   94.0
24  1.0  117.0  376.0
25  5.0   13.0  141.0
26  3.0  104.0  188.0
27  0.0    0.0  329.0
28  3.0    0.0    0.0
29  3.0   13.0  329.0
30  3.0   13.0  141.0
31  1.0   78.0   94.0
32  1.0   91.0   94.0
33  0.0    0.0  329.0
34  3.0   78.0  329.0
35  3.0    0.0  141.0
36  0.0    0.0  282.0
37  1.0   78.0  188.0
38  9.0   78.0  188.0
39  9.0   13.0    0.0
40  8.0   52.0  188.0
41  5.0    0.0   94.0
42  2.0    0.0  329.0
43  3.0   13.0  329.0
44  8.0   91.0  376.0
45  0.0   91.0  376.0
46  1.0   26.0  141.0
47  1.0   26.0  141.0
48  8.0   13.0    0.0
49  2.0   13.0  141.0